import time


print("positive energy used")
time.sleep(1)
print("positive turns into negative")
time.sleep(1)
print("left over energy from positive goes to negative")
time.sleep(1)
print("negative turns into positive")
time.sleep(1)
print("positive energy used")
time.sleep(1)
print("positive turns into negative")
time.sleep(1)
print("left over energy from positive goes to negative")
time.sleep(1)
print("negative turns into positive")
time.sleep(1)
print("positive energy used")
time.sleep(1)
print("positive turns into negative")
time.sleep(1)
print("left over energy from positive goes to negative")
time.sleep(1)
print("negative turns into positive")
time.sleep(1)
print("positive energy used")
time.sleep(1)
print("positive turns into negative")
time.sleep(1)
print("left over energy from positive goes to negative")
time.sleep(1)
print("negative turns into positive")
time.sleep(1)
print("positive energy used")
time.sleep(1)
print("positive turns into negative")
time.sleep(1)
print("left over energy from positive goes to negative")
time.sleep(1)
print("negative turns into positive")
time.sleep(1)
print("positive energy used")
time.sleep(1)
print("positive turns into negative")
time.sleep(1)
print("left over energy from positive goes to negative")
time.sleep(1)
print("negative turns into positive")
time.sleep(1)
print("positive energy used")
time.sleep(1)
print("positive turns into negative")
time.sleep(1)
print("left over energy from positive goes to negative")
time.sleep(1)
print("negative turns into positive")
time.sleep(1)
print("positive energy used")
time.sleep(1)
print("positive turns into negative")
time.sleep(1)
print("left over energy from positive goes to negative")
time.sleep(1)
print("negative turns into positive")
time.sleep(1)
print("positive energy used")
time.sleep(1)
print("positive turns into negative")
time.sleep(1)
print("left over energy from positive goes to negative")
time.sleep(1)
print("negative turns into positive")
time.sleep(1)
print("positive energy used")
time.sleep(1)
print("positive turns into negative")
time.sleep(1)
print("left over energy from positive goes to negative")
time.sleep(1)
print("negative turns into positive")
time.sleep(1)
print("positive energy used")
time.sleep(1)
print("positive turns into negative")
time.sleep(1)
print("left over energy from positive goes to negative")
time.sleep(1)
print("negative turns into positive")
time.sleep(1)


